#!/usr/bin/env python

from __future__ import print_function

import os
import subprocess

EOSPATH="/eos/vbc/experiments/cms/store/user/liko/StopsCompressed/nanoTuples"
SCRATCHPATH="/scratch-cbe/users/dietrich.liko/StopsCompressed/nanoTuples"

for root, dirs, files in os.walk(EOSPATH):

    if len(files):
        print('Checking %s ...' % root[len(EOSPATH)+1:])
    
    for name in files:
        eospath = os.path.join(root, name)
        relative_path = eospath[len(EOSPATH)+1:]
        scratchpath = os.path.join(SCRATCHPATH, relative_path)

        # remove bad files

        size = os.stat(eospath).st_size
        if os.path.exists(scratchpath):
            if os.stat(scratchpath).st_size != size:
                print('Size mismatch NFS-SCRATCH. Removing SCRATCH file %s' % scratchpath) 
                os.remove(scratchpath)

        # copy files
        if not os.path.exists(scratchpath):
            print("Copying to SCRATCH %s" % relative_path)
            scratchdir = os.path.dirname(scratchpath)
            if not os.path.exists(scratchdir):
                os.makedirs(scratchdir)
            subprocess.check_call([
                'xrdcp', 
                '--nopbar',
                '--retry',
                '3', 
                'root://eos.grid.vbc.ac.at/'+eospath,
                 scratchpath
            ])

        os.utime(scratchpath, None)
